ThemeStore/ThemeStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('games/', include("games.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ThemeStore/games/urls.py
from django.urls import path
from . import views


app_name = "games"

urlpatterns = [
    path("create/", views.create_game_view, name="create_game_view"),
    path("all/", views.view_games, name="all_game_view"),
]

ThemeStore/main/urls.py
from . import views
from django.urls import path

app_name = "main"

urlpatterns = [
    path("", views.home_view, name="home_view"),
    path("themes/", views.themes_view, name="themes_view"),
    path("contact/", views.contact_view, name="contact_view"),
    path("font/large/", views.large_font_view, name="large_font_view"),
    path("font/normal/", views.normal_font_view, name="normal_font_view"),

]

ThemeStore/games/models.py
from django.db import models

# Create your models here.

class Game(models.Model):

    title = models.CharField(max_length=1024)
    description = models.TextField()
    publisher = models.CharField(max_length=256)
    rating = models.SmallIntegerField()
    release_date = models.DateField()
    poster = models.ImageField(upload_to="images/", default="images/default.jpg")

ThemeStore/main/models.py
from django.db import models

# Create your models here.

ThemeStore/games/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse

from .models import Game

# Create your views here.

def create_game_view(request:HttpRequest):


    if request.method == "POST":
        new_game = Game(title=request.POST["title"], description=request.POST["description"], publisher=request.POST["publisher"], rating=request.POST["rating"], release_date=request.POST["release_date"], poster=request.FILES["poster"])
        new_game.save()
        return redirect("games:all_game_view")

    return render(request, "games/create.html")


def view_games(request:HttpRequest):


    return render(request, "games/all.html", {"games": Game.objects.all()})

ThemeStore/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse

# Create your views here.


def home_view(request:HttpRequest):

    response =  render(request, "main/index.html")
    return response



def themes_view(request: HttpRequest):


    return render(request, "main/themes_page.html")


def contact_view(request: HttpRequest):

    return render(request, "main/contact_page.html")


def large_font_view(request: HttpRequest):

    response = redirect("main:home_view")
    response.set_cookie("font", "large", max_age=60*60*24)

    return response


def normal_font_view(request: HttpRequest):

    response = redirect("main:home_view")
    response.set_cookie("font", "large", max_age=-3600)

    return response

ThemeStore/games/templates/games/all.html
{% extends 'main/base.html' %}

{% block title %} Bootstrap Preview {% endblock %}

{% block content %}



<div class="row   row-cols-1 row-cols-md-2  hero-row">
    <div class="col order-2 order-md-1 ">
        <div class="d-flex flex-column justify-content-center align-items-center h-100">
            <h1 class="text-center">The Place for Gamers!</h1>
            <h3 class="text-center">For all the games informations you need</h3>
        </div>

    </div>

    <div class="col order-1 overflow-hidden hero h-100 p-0">
        <!-- <img class="w-100 h-100 object-fit-cover" src="https://static0.srcdn.com/wordpress/wp-content/uploads/2023/11/greatest-movies-of-all-time.jpg" /> -->
        <div class="vid-container">
          <video class="h-100" src="/static/videos/backvid.mp4" muted autoplay loop></video>
        </div>
    </div>
</div>

<hr />
<h2>Our Games</h2>
<div class="row mt-5 row-cols-1 row-cols-md-3 g-4">

  {% for game in games %}
    <div class="col">
        <div class="d-flex flex-column justify-content-start align-items-start h-100 p-4 shadow">
            <img src="{{game.poster.url}}" class="w-100" style="width:250px; height: 250px; object-fit:cover"/>
            <h3>{{game.title}}</h3>
            <p>{{game.description}}</p>
            <h5>Published by: {{game.publisher}}</h5>
            <h6>{{game.release_date}}</h6>
        </div>
    </div>
  {% endfor %}


</div>

{% endblock %}

ThemeStore/games/templates/games/create.html
{% extends 'main/base.html' %}


{% block title %}Create New Game{% endblock %}

{% block content %}
<h1>Create Game</h1>

<div class="row">

    <div class="col-6">

        <form class="d-flex flex-column gap-2" action="{% url 'games:create_game_view' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" placeholder="Title" name="title" class="form-control" />
            <textarea placeholder="Description" name="description" class="form-control"></textarea>
            <input type="text" placeholder="Publisher" name="publisher" class="form-control" />
            <select class="form-select" name="rating">
                <option selected>Rating</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
                <option value="4">Four</option>
                <option value="5">Five</option>
              </select>

            <label>Poster:</label>
            <input type="file" name="poster"  class="form-control" accept="image/*"/>
            <input type="date" name="release_date" class="form-control"/>

            <input type="submit" value="Create Game" class="btn btn-primary" />

        </form>


    </div>

</div>

{% endblock %}

ThemeStore/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en" {% if 'font' in  request.COOKIES %} class="large" {% endif %}>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="/static/css/style.css" rel="stylesheet" />
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <div class="wrapper">
        <nav>
            <a href="/"><strong class="logo">Theme Store</strong></a>

            <div class="right-nav">
                <a href="">Home</a>
                <a href="">About</a>
                <a href="">Services</a>
                <a href="">How it Works</a>
                <a href="{% url 'main:contact_view' %}">Contact</a>
                <button class="btn">Try for Free</button>
            </div>
        </nav> <!-- End Nav -->

        <main>
            {% block content %}

            {% endblock %}
        </main>


        <footer>
            <div class="container">
                <a href="#">Home</a>
                <a href="#">Contact Us</a>
                <a href="#">Our Themes</a>
            </div>

            <div>
                All Rights Reserved.
            </div>

            <div class="container">
                <h3>Font</h3>
                <div class="font-icons-container">
                    <a href="{% url 'main:normal_font_view' %}"><span class="material-symbols-outlined {% if not 'font' in request.COOKIES %} active-icon {% endif %}">format_size</span></a>
                    <a href="{% url 'main:large_font_view' %}"><span class="material-symbols-outlined large-icon {% if 'font' in request.COOKIES %} active-icon {% endif %}">format_size</span></a>
                </div>
            </div>

        </footer>


    </div> <!-- End Wrapper -->
    
</body>
</html>

ThemeStore/main/templates/main/contact_page.html
{% extends 'main/base.html' %}

{% block title %} Contact Us page{% endblock %}

{% block content %}

<section>
    <h1>Contact Us</h1>
    <form>
        <input type="text" placeholder="Your email" />
        <textarea placeholder="Your message"></textarea>
    </form>
</section>

{% endblock %}

ThemeStore/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}Theme Store Homepage {% endblock %}

{% block content %}
<section class="top-content">
    <div class="top-content-header">
        <h1>Best Themes For Your Smartphone</h1>
        <h2>Random change</h2>
        <div class="top-content-util">
            <a href="" class="btn">Get started</a>

            <a href="" class="btn light">
                <div class="play-phrase">
                    <span class="material-symbols-outlined">play_arrow</span>
                    <h6>How to set up</h6>
                </div>
            </a>
        </div>
    </div>


    <a href="#mid-section">
    <div class="bottom-anchor">
        <h6>How It Works</h6>
        <span class="material-symbols-outlined">keyboard_double_arrow_down</span> 
    </div>
    </a>

</section>


<section class="mid-section" id="mid-section">

    <div class="mid-seciton-content">
        <h2>100+ Themes and Wallpapers</h2>
        <p>A great phone. A great phone. A great phone. A great phone. A great phone. A great phone. A great phone. A great phone. A great phone. A great phone.</p>
        <a href="{% url 'main:themes_view' %}" class="btn">Know more</a>
    </div>
    
    <img src="/static/images/phone-1024.png" />

</section>
{% endblock %}

ThemeStore/main/templates/main/themes_page.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Our Themes Page{% endblock %}

{% block content %}
    <section>
        <h1>Our Themes</h1>
        <div class="themes-container">
            <div class="card">
                <img src="{% static 'images/wallpaper1.jpg' %}" />
                <h4>Theme 1</h4>
            </div>


            <div class="card">
                <img src="{% static 'images/wallpaper2.jpg' %}" />
                <h4>Theme 2</h4>
            </div>


            <div class="card">
                <img src="{% static 'images/wallpaper3.jpg' %}" />
                <h4>Theme 3</h4>
            </div>
        </div>

    </section>

{% endblock %}